name: transition-jira-issues-on-pr-merge

on:
  pull_request_target:
      types:
      - closed
      branches:
      - main
      - release
  workflow_dispatch:
    inputs:
      reason:
        description: 'The reason for running the workflow'
        required: true
        default: 'Force do stuff'

jobs:
  transition-jira-issues-on-pr-merge:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      # - name: Dump GitHub context
      #   env:
      #     GITHUB_CONTEXT: ${{ toJson(github) }}
      #   run: |
      #     echo "$GITHUB_CONTEXT"
      - uses: actions/checkout@v3
      - name: do the thing
        id: fancy-things
        uses: Raganhar/nup-github-action-jira-transition@v1
        env:
          GITHUB_CONTEXT: "${{ toJson(github) }}"
        with:
          jira-api-key: ${{ secrets.JIRA_API_TOKEN }}
          jira-url: ${{ secrets.JIRA_BASE_URL }}
          jira-user: ${{ secrets.JIRA_USER_EMAIL }}
          main-jira-transition: done
          release-jira-transition: in progress
          jira_state_when_revert: to do